infinispan:
   remote:
     server-list: 127.0.0.1:11222
     # Read https://blog.infinispan.org/2018/03/accessing-infinispan-inside-docker-for.html
     client-intelligence: BASIC
     near-cache-mode: INVALIDATED
     near-cache-max-entries: 10
     near-cache-cache-name-pattern: i8n-.*